---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: debian-stretch
    image: debian:stretch

provisioner:
  name: ansible
  options:
    diff: True
    v: True
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  options:
    disable-pytest-warnings: True
    v: True
  lint:
    name: flake8
